// Generated by scripts/sync-profiles.mjs from your Comet profiles. Do not edit; run `npm run sync`.
import { LaunchProps } from "@raycast/api";
import { runProfileCommand } from "./launch";

export default async function Command(props: LaunchProps<{ arguments: { url?: string } }>) {
  await runProfileCommand("Default", "netwatcher", props.arguments.url);
}
